name: lint

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort mypy pylint

      - name: Checks
        run: |
          flake8 .
          mypy --config mypy.ini women/
          pylint --rcfile .pylintrc women/ coolsite/
